import express from "express";
const router=express.Router();
import {login,register,getEveryEvent,addEvent,eventDetail,joinEvent,searchEvent,myEvents,deleteEvent,updateEvent,attendeeEvent,deleteAttendingEvent,events, guestSearchEvent} from '../controllers/userController.js';
import Authenticate from "../middleware/Authenticate.js";
router.post('/login',login);
router.post('/register',register);
router.get('/getEveryEvent/:id',getEveryEvent);
router.post('/addEvent/:id',addEvent);
router.get('/eventDetail/:id',eventDetail);
router.post('/joinEvent/:eventid/:id',joinEvent);
router.get('/searchEvent/:term/:id',searchEvent);
router.get('/myEvents/:id',myEvents);
router.delete('/deleteEvent/:id',Authenticate,deleteEvent);
router.put('/updateEvent/:id',Authenticate,updateEvent);
router.get('/attendeeEvent/:id',attendeeEvent);
router.delete('/deleteAttendingEvent/:id',Authenticate,deleteAttendingEvent);
router.get('/events',events);
router.get('/guestSearchEvent/:term',guestSearchEvent);
export default router;